import {
  Program,
  BuilderProfile,
  Team,
  ProjectSubmission,
  Mentor,
  MentorSession,
  NotificationItem,
  DemoApplication,
} from "@/types";

export const DEMO_PROGRAMS: Program[] = [
  {
    id: "prog-ai-northstar",
    slug: "bogota-ai-operations",
    title: "Bogotá AI Operations Challenge",
    oneLiner: "Construye agentes autónomos y pipelines de IA para transformar la eficiencia operativa.",
    organizationId: "org-northstar",
    organizationName: "Northstar Labs",
    coverImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=80",
    logo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=200&q=80",
    status: "BUILDING",
    format: "HIBRIDO",
    city: "Bogotá",
    country: "Colombia",
    startDate: "2026-10-12",
    endDate: "2026-10-26",
    applicationDeadline: "2026-10-05",
    prizePool: "$35,000 USD + Piloto Corporativo",
    category: "AI",
    theme: {
      primary: "#2563EB",
      accent: "#38BDF8",
      badgeBg: "bg-blue-50 text-blue-700 border-blue-200",
      gradient: "from-blue-600 to-indigo-700",
    },
    description:
      "Una iniciativa de innovación abierta diseñada para reunir a los mejores ingenieros, investigadores y diseñadores de producto de América Latina con un solo objetivo: construir soluciones operativas reales impulsadas por modelos de lenguaje e inteligencia artificial agéntica.",
    whyParticipate: [
      "Acceso a datasets y APIs empresariales exclusivas de Northstar Labs.",
      "Oportunidad de pasar de prototipo a piloto remunerado con presupuesto de implementación.",
      "Mentorías directas de Tech Leads, Research Scientists y directores de producto.",
      "Premios en efectivo entregados sin retención de propiedad intelectual para tu startup.",
    ],
    eligibility: [
      "Equipos de 2 a 5 integrantes (se permite aplicar individualmente y hacer matchmaking).",
      "Desarrolladores de software, ingenieros de machine learning, diseñadores UX y fundadores técnicos.",
      "Disponibilidad para la sesión de cierre y pitch presencial en Bogotá o transmisión en vivo de alta fidelidad.",
    ],
    stats: {
      views: 1420,
      applications: 428,
      accepted: 140,
      checkedIn: 128,
      teams: 34,
      submissions: 26,
      finalists: 8,
    },
    challenges: [
      {
        id: "ch-01",
        programId: "prog-ai-northstar",
        title: "Automatización de auditoría documental con IA multimodal",
        trackNumber: "Reto 01",
        shortDescription: "Procesar y validar contratos, facturas y pólizas complejas en segundos con verificación de sesgos.",
        problem: "Las organizaciones pierden más de 18 horas por semana verificando manualmente documentos legales y financieros con formatos no estructurados.",
        context: "Northstar Labs maneja millones de transacciones donde la extracción precisa de entidades y cláusulas críticas es vital para el cumplimiento regulatorio.",
        objective: "Diseñar un pipeline agéntico multimodal que extraiga, concilie y alerte sobre discrepancias en documentos complejos con precisión superior al 98%.",
        expectedOutcome: "Un prototipo funcional con API, interfaz web de validación y dashboard de auditoría con explicación trazable de cada decisión del modelo.",
        recommendedTech: ["Python", "FastAPI", "Next.js", "LangChain / LlamaIndex", "OpenAI / Claude API", "pgvector"],
        deliverables: ["Código en GitHub con README detallado", "Demo interactiva desplegada", "Video pitch de 3 minutos", "Documento de arquitectura técnica"],
        prizePool: "$15,000 USD",
      },
      {
        id: "ch-02",
        programId: "prog-ai-northstar",
        title: "Agentes de resolución de disputas y atención en tiempo real",
        trackNumber: "Reto 02",
        shortDescription: "Agentes autónomos con memoria a largo plazo que resuelven solicitudes complejas de clientes sin escalamiento.",
        problem: "El soporte tradicional con chatbots de primera generación genera frustración al no tener contexto profundo ni capacidad transaccional segura.",
        context: "Buscamos agentes capaces de consultar bases de conocimiento vivas y ejecutar acciones autorizadas con salvaguardas estrictas.",
        objective: "Construir un agente capaz de interactuar vía chat/voz, autenticar contextualmente la intención del usuario y ejecutar flujos de resolución de 3+ pasos.",
        expectedOutcome: "Sistema interactivo con simulación de 10 casos extremos resueltos con éxito y registro de auditoría de herramientas utilizadas.",
        recommendedTech: ["TypeScript", "Next.js", "WebSockets", "Vercel AI SDK", "Supabase / Redis"],
        deliverables: ["Repositorio de código", "Entorno sandbox para pruebas del jurado", "Métricas de latencia y precisión"],
        prizePool: "$12,000 USD",
      },
      {
        id: "ch-03",
        programId: "prog-ai-northstar",
        title: "Optimización predictiva de cadenas de suministro urbanas",
        trackNumber: "Reto 03",
        shortDescription: "Modelos de predicción de demanda y reabastecimiento en condiciones de alta volatilidad en ciudades de LATAM.",
        problem: "El tráfico impredecible y los patrones de compra cambiantes generan sobrecostos logísticos del 22% en última milla en Bogotá y Medellín.",
        context: "Se facilitará un dataset anonimizado de 500,000 órdenes geolocalizadas con tiempos reales de entrega e incidencias.",
        objective: "Crear un algoritmo y visualizador de despacho dinámico que reduzca tiempos muertos y consumo de combustible mediante optimización heurística/ML.",
        expectedOutcome: "Dashboard de simulación y motor de recomendaciones con API REST documentada.",
        recommendedTech: ["Python", "Pandas", "PyTorch / Scikit-learn", "Mapbox GL", "Tailwind CSS"],
        deliverables: ["Jupyter Notebook con análisis de error", "Simulador en vivo", "Presentación ejecutiva"],
        prizePool: "$8,000 USD",
      },
    ],
    rubric: [
      {
        id: "rub-impact",
        name: "Impacto y Viabilidad de Negocio",
        description: "Relevancia directa del problema y potencial de escalar a un piloto corporativo medible.",
        weight: 25,
        maxScore: 10,
        guidelines: { 10: "Solución lista para piloto con ROI claro", 5: "Buena idea pero difícil implementación", 1: "Desconectado del problema" },
      },
      {
        id: "rub-tech",
        name: "Ejecución Técnica y Arquitectura",
        description: "Calidad del código, solidez del stack, buenas prácticas, seguridad y manejo de fallos.",
        weight: 25,
        maxScore: 10,
        guidelines: { 10: "Arquitectura modular impecable y reproducible", 5: "Funciona parcialmente con fallas menores", 1: "Código roto o no funcional" },
      },
      {
        id: "rub-inno",
        name: "Innovación y Originalidad",
        description: "Uso creativo de IA, diferenciación frente a soluciones convencionales y propuesta de valor única.",
        weight: 20,
        maxScore: 10,
        guidelines: { 10: "Enfoque verdaderamente novedoso", 5: "Variación estándar de herramientas existentes", 1: "Copia directa sin aporte" },
      },
      {
        id: "rub-ux",
        name: "Experiencia de Usuario y Diseño",
        description: "Claridad en la interfaz, ergonomía del flujo de trabajo y facilidad de adopción.",
        weight: 15,
        maxScore: 10,
        guidelines: { 10: "Diseño profesional intuitivo y accesible", 5: "Funcional pero confuso en puntos clave", 1: "Inutilizable" },
      },
      {
        id: "rub-pitch",
        name: "Claridad del Pitch y Demostración",
        description: "Capacidad de comunicar la solución, síntesis y demostración en vivo convincente.",
        weight: 15,
        maxScore: 10,
        guidelines: { 10: "Demostración impecable en tiempo récord", 5: "Presentación densa pero con demo", 1: "Confuso sin demo clara" },
      },
    ],
    sponsors: [
      {
        id: "sp-01",
        name: "Northstar Ventures",
        logo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&q=80",
        tier: "TITLE",
        perks: "Premios en efectivo + Acompañamiento a piloto de 3 meses",
        website: "https://northstarlabs.demo",
      },
      {
        id: "sp-02",
        name: "Andes Cloud Partners",
        logo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&q=80",
        tier: "TECHNOLOGY",
        perks: "$2,500 USD en créditos de cómputo GPU por equipo",
        website: "https://cloudpartners.demo",
      },
      {
        id: "sp-03",
        name: "InnovaBogotá Hub",
        logo: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&q=80",
        tier: "COMMUNITY",
        perks: "Espacio de coworking físico y soporte legal en Colombia",
        website: "https://innovabogota.demo",
      },
    ],
  },
  {
    id: "prog-climate-caribe",
    slug: "caribe-climate-cleantech",
    title: "Caribe Climate & CleanTech Challenge",
    oneLiner: "Soluciones de datos y tecnología para la resiliencia costera y energía limpia en el Caribe colombiano.",
    organizationId: "org-ecosistema",
    organizationName: "Ecosistema Caribe Innova",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80",
    logo: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=200&q=80",
    status: "APPLICATIONS_OPEN",
    format: "HIBRIDO",
    city: "Barranquilla",
    country: "Colombia",
    startDate: "2026-11-05",
    endDate: "2026-11-19",
    applicationDeadline: "2026-10-25",
    prizePool: "$20,000 USD + Aceleración",
    category: "Climate",
    theme: {
      primary: "#059669",
      accent: "#34D399",
      badgeBg: "bg-emerald-50 text-emerald-700 border-emerald-200",
      gradient: "from-emerald-600 to-teal-700",
    },
    description: "Desafío enfocado en monitoreo de erosión costera, eficiencia de micro-redes solares y conservación de manglares.",
    whyParticipate: ["Validación en campo con comunidades y empresas del sector energético", "Fondo semilla para los dos primeros lugares"],
    eligibility: ["Abierto a estudiantes universitarios, investigadores y startups en etapa temprana."],
    stats: { views: 890, applications: 184, accepted: 60, checkedIn: 0, teams: 18, submissions: 0, finalists: 0 },
    challenges: [],
    rubric: [],
    sponsors: [],
  },
  {
    id: "prog-fintech-inclusion",
    slug: "fintech-inclusion-cup",
    title: "Fintech Inclusion Cup Colombia",
    oneLiner: "Modelos alternativos de scoring y micro-crédito para economía popular y micro-comercios.",
    organizationId: "org-fintech-hub",
    organizationName: "Alianza Fintech LATAM",
    coverImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1600&q=80",
    logo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=200&q=80",
    status: "COMPLETED",
    format: "PRESENCIAL",
    city: "Medellín",
    country: "Colombia",
    startDate: "2026-08-10",
    endDate: "2026-08-24",
    applicationDeadline: "2026-08-01",
    prizePool: "$25,000 USD",
    category: "Fintech",
    theme: {
      primary: "#4F46E5",
      accent: "#818CF8",
      badgeBg: "bg-indigo-50 text-indigo-700 border-indigo-200",
      gradient: "from-indigo-600 to-purple-700",
    },
    description: "Diseño de productos financieros transparentes y accesibles para más de 4 millones de emprendedores no bancarizados.",
    whyParticipate: ["Integración con APIs bancarias de prueba", "Reconocimiento ante fondos de capital de riesgo"],
    eligibility: ["Equipos interdisciplinarios de finanzas, producto y desarrollo."],
    stats: { views: 2400, applications: 512, accepted: 120, checkedIn: 114, teams: 28, submissions: 24, finalists: 6 },
    challenges: [],
    rubric: [],
    sponsors: [],
  },
  {
    id: "prog-govtech-bogota",
    slug: "govtech-tramites-cero",
    title: "GovTech Civic Solutions Lab",
    oneLiner: "Simplificación digital de trámites ciudadanos con interoperabilidad y accesibilidad universal.",
    organizationId: "org-gov-lab",
    organizationName: "Laboratorio de Innovación Pública",
    coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80",
    logo: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=200&q=80",
    status: "APPLICATIONS_OPEN",
    format: "ONLINE",
    city: "Bogotá",
    country: "Colombia",
    startDate: "2026-11-20",
    endDate: "2026-12-04",
    applicationDeadline: "2026-11-10",
    prizePool: "$18,000 USD en contratos de innovación",
    category: "GovTech",
    theme: {
      primary: "#7C3AED",
      accent: "#A78BFA",
      badgeBg: "bg-purple-50 text-purple-700 border-purple-200",
      gradient: "from-purple-600 to-violet-800",
    },
    description: "Convocatoria para reinventar la relación entre el ciudadano y los servicios públicos con diseño centrado en personas.",
    whyParticipate: ["Adopción real en servicios de ventanilla única", "Acompañamiento normativo"],
    eligibility: ["Desarrolladores cívicos, analistas de datos y diseñadores de servicios."],
    stats: { views: 670, applications: 142, accepted: 45, checkedIn: 0, teams: 12, submissions: 0, finalists: 0 },
    challenges: [],
    rubric: [],
    sponsors: [],
  },
];

export const DEMO_BUILDERS: BuilderProfile[] = [
  {
    id: "b-01",
    handle: "mateo_dev",
    name: "Mateo Valencia",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    headline: "Senior Fullstack & AI Systems Builder",
    city: "Bogotá",
    country: "Colombia",
    role: "Fullstack",
    skills: ["TypeScript", "Next.js", "Python", "LangChain", "FastAPI", "PostgreSQL"],
    github: "https://github.com/mateo-valencia",
    linkedin: "https://linkedin.com/in/mateovalencia",
    lookingForTeam: false,
    stats: { hackathons: 6, projects: 5, finalist: 4, wins: 2 },
    verifiedBadges: [
      { id: "vb-1", label: "1er Puesto", programTitle: "Fintech Inclusion Cup Colombia", year: "2026", type: "WINNER" },
      { id: "vb-2", label: "Finalista", programTitle: "Bogotá AI Operations", year: "2026", type: "FINALIST" },
    ],
  },
  {
    id: "b-02",
    handle: "camila_ux",
    name: "Camila Restrepo",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
    headline: "Product Designer & Design Systems Specialist",
    city: "Medellín",
    country: "Colombia",
    role: "UX/Design",
    skills: ["Figma", "Design Systems", "Prototyping", "User Research", "Tailwind CSS"],
    github: "https://github.com/camirestrepo",
    linkedin: "https://linkedin.com/in/camilarestrepo-ux",
    lookingForTeam: true,
    stats: { hackathons: 4, projects: 4, finalist: 3, wins: 1 },
    verifiedBadges: [
      { id: "vb-3", label: "Mejor UX", programTitle: "Fintech Inclusion Cup", year: "2026", type: "CONTRIBUTOR" },
    ],
  },
  {
    id: "b-03",
    handle: "andres_ml",
    name: "Andrés Echeverry",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    headline: "Machine Learning Engineer & RAG Architect",
    city: "Cali",
    country: "Colombia",
    role: "AI/ML",
    skills: ["PyTorch", "HuggingFace", "Python", "Vector DBs", "Docker", "Embeddings"],
    github: "https://github.com/aecheverry-ml",
    linkedin: "https://linkedin.com/in/andresecheverry",
    lookingForTeam: false,
    stats: { hackathons: 5, projects: 4, finalist: 3, wins: 1 },
    verifiedBadges: [
      { id: "vb-4", label: "Finalista", programTitle: "Bogotá AI Operations", year: "2026", type: "FINALIST" },
    ],
  },
  {
    id: "b-04",
    handle: "daniela_pm",
    name: "Daniela Morales",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80",
    headline: "Tech Product Manager & Business Strategist",
    city: "Bogotá",
    country: "Colombia",
    role: "Product",
    skills: ["Product Discovery", "Metrics / OKRs", "Scrum", "Pitching", "Growth"],
    linkedin: "https://linkedin.com/in/danielamorales-pm",
    lookingForTeam: true,
    stats: { hackathons: 3, projects: 3, finalist: 2, wins: 1 },
    verifiedBadges: [
      { id: "vb-5", label: "Mejor Pitch", programTitle: "Fintech Cup", year: "2026", type: "CONTRIBUTOR" },
    ],
  },
  {
    id: "b-05",
    handle: "santiago_back",
    name: "Santiago Orozco",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    headline: "Backend & Cloud Architect (Go / Rust / AWS)",
    city: "Bucaramanga",
    country: "Colombia",
    role: "Backend",
    skills: ["Go", "Kubernetes", "PostgreSQL", "Kafka", "AWS", "gRPC"],
    github: "https://github.com/sorozco-dev",
    lookingForTeam: true,
    stats: { hackathons: 2, projects: 2, finalist: 1, wins: 0 },
    verifiedBadges: [],
  },
];

export const DEMO_TEAMS: Team[] = [
  {
    id: "team-docuflow",
    programId: "prog-ai-northstar",
    name: "DocuFlow AI",
    challengeId: "ch-01",
    challengeTitle: "Automatización de auditoría documental con IA multimodal",
    members: [
      {
        builderId: "b-01",
        name: "Mateo Valencia",
        handle: "mateo_dev",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
        role: "Team Lead & Fullstack",
        isLead: true,
      },
      {
        builderId: "b-03",
        name: "Andrés Echeverry",
        handle: "andres_ml",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
        role: "AI Engineer",
        isLead: false,
      },
    ],
    lookingForRoles: ["UX/Design", "Product"],
    skillsCoverage: {
      backend: true,
      frontend: true,
      ai: true,
      design: false,
      product: false,
    },
    submissionId: "proj-docuflow",
    mentorAssigned: "Carlos Peña (VP Engineering)",
    inviteCode: "DOCU-8921",
  },
  {
    id: "team-neural-andes",
    programId: "prog-ai-northstar",
    name: "Neural Andes",
    challengeId: "ch-02",
    challengeTitle: "Agentes de resolución de disputas y atención en tiempo real",
    members: [
      {
        builderId: "b-02",
        name: "Camila Restrepo",
        handle: "camila_ux",
        avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
        role: "Product Designer",
        isLead: true,
      },
    ],
    lookingForRoles: ["Backend", "AI/ML"],
    skillsCoverage: {
      backend: false,
      frontend: true,
      ai: false,
      design: true,
      product: true,
    },
    inviteCode: "ANDES-4102",
  },
  {
    id: "team-logix-ai",
    programId: "prog-ai-northstar",
    name: "Logix Dynamic Dispatch",
    challengeId: "ch-03",
    challengeTitle: "Optimización predictiva de cadenas de suministro urbanas",
    members: [
      {
        builderId: "b-05",
        name: "Santiago Orozco",
        handle: "santiago_back",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
        role: "Backend Lead",
        isLead: true,
      },
    ],
    lookingForRoles: ["AI/ML", "Frontend"],
    skillsCoverage: {
      backend: true,
      frontend: false,
      ai: false,
      design: false,
      product: false,
    },
    inviteCode: "LOGIX-7731",
  },
];

export const DEMO_PROJECTS: ProjectSubmission[] = [
  {
    id: "proj-docuflow",
    programId: "prog-ai-northstar",
    teamId: "team-docuflow",
    teamName: "DocuFlow AI",
    title: "DocuFlow AI: Pipeline Autónomo de Conciliación Documental",
    oneLinePitch: "Extracción agéntica multimodal de contratos y conciliación automática con verificación de cláusulas de riesgo en segundos.",
    problem:
      "Las empresas medianas y grandes en Colombia dedican en promedio 4.5 días hábiles a cotejar manualmente contratos marco contra órdenes de servicio y facturas fiscales, generando cuellos de botella legales y multas por errores de digitación.",
    solution:
      "DocuFlow combina visión artificial y LLMs especializados en legislación comercial para descomponer contratos en grafos de conocimiento verificables, detectando discrepancias entre obligaciones y pagos con trazabilidad auditable.",
    impact:
      "Reduce el tiempo de auditoría de 4.5 días a 18 segundos por legajo, con una tasa de detección de anomalías del 99.2% demostrada en las pruebas de validación.",
    architecture:
      "Frontend en Next.js 15 conectado vía gRPC/REST a microservicios FastAPI. Los documentos se procesan en paralelo con extracción OCR mejorada, indexación vectorial en PostgreSQL con pgvector y agentes de orquestación con memoria determinista.",
    stack: ["TypeScript", "Next.js", "FastAPI", "Python", "LangChain", "pgvector", "PostgreSQL", "Docker", "Tailwind CSS"],
    demoUrl: "https://docuflow.demo.kamino.co",
    repoUrl: "https://github.com/northstar-demo/docuflow-ai",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    deckUrl: "https://speakerdeck.com/docuflow-pitch",
    screenshots: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    ],
    aiDisclosure:
      "Se utilizaron modelos Claude 3.5 Sonnet y GPT-4o a través de API con embeddings text-embedding-3-large para clasificación y extracción. Todo el código base, infraestructura y lógica de negocio fue desarrollado por el equipo durante el reto.",
    completenessPercent: 88,
    pipelineStage: "PILOT",
    scores: {
      averageScore: 9.4,
      evaluationsCount: 3,
      variance: 0.2,
    },
    awardPlacement: "1er Puesto — Reto 01",
    createdAt: "2026-10-24T18:30:00Z",
    updatedAt: "2026-10-25T14:15:00Z",
  },
  {
    id: "proj-ecoruta",
    programId: "prog-climate-caribe",
    teamId: "team-eco",
    teamName: "EcoRuta Andes",
    title: "EcoRuta: Optimización de Energía Renovable para Microredes",
    oneLinePitch: "Balanceo de carga inteligente para comunidades costeras con generación solar descentralizada.",
    problem: "Las microredes solares comunitarias sufren cortes recurrentes debido a desbalance de carga y falta de predicción meteorológica hiperlocal.",
    solution: "Algoritmo de predicción de irradiación a 6 horas y balanceo automático de demanda no prioritaria mediante switches IoT.",
    impact: "Aumento del 34% en la autonomía energética de 120 familias de la comunidad piloto de prueba.",
    architecture: "Edge computing con Raspberry Pi 5 + ESP32, ingestión MQTT en backend Rust y panel de control web PWA.",
    stack: ["Rust", "MQTT", "ESP32", "React", "TimescaleDB", "Tailwind CSS"],
    demoUrl: "https://ecoruta.demo.kamino.co",
    repoUrl: "https://github.com/ecosistema/ecoruta",
    screenshots: ["https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=1200&q=80"],
    aiDisclosure: "Uso de modelos Random Forest y LSTM entrenados localmente con datos históricos del IDEAM.",
    completenessPercent: 100,
    pipelineStage: "INCUBATION",
    scores: { averageScore: 9.1, evaluationsCount: 4, variance: 0.3 },
    awardPlacement: "Ganador Absoluto CleanTech",
    createdAt: "2026-09-12T16:00:00Z",
    updatedAt: "2026-09-14T11:00:00Z",
  },
];

export const DEMO_SCHEDULE = [
  {
    id: "sch-1",
    programId: "prog-ai-northstar",
    day: 1,
    date: "12 Octubre",
    time: "08:30 AM",
    title: "Acreditación y Café de Bienvenida",
    type: "OPENING" as const,
    location: "Hub Central Bogotá / Sala Virtual 1",
    isLive: false,
  },
  {
    id: "sch-2",
    programId: "prog-ai-northstar",
    day: 1,
    date: "12 Octubre",
    time: "09:30 AM",
    title: "Kickoff Oficial & Presentación de Retos Técnicos",
    type: "OPENING" as const,
    location: "Auditorio Principal & Livestream",
    speaker: "Laura Gómez (Directora de Innovación, Northstar Labs)",
    isLive: false,
  },
  {
    id: "sch-3",
    programId: "prog-ai-northstar",
    day: 1,
    date: "12 Octubre",
    time: "11:30 AM",
    title: "Workshop: Construyendo Agentes Autónomos con Guardrails",
    type: "WORKSHOP" as const,
    location: "Sala de Workshops",
    speaker: "Felipe Morales (Staff AI Engineer)",
    isLive: false,
  },
  {
    id: "sch-4",
    programId: "prog-ai-northstar",
    day: 2,
    date: "13 Octubre",
    time: "03:00 PM",
    title: "Sesiones 1:1 de Mentoría de Arquitectura",
    type: "MENTORSHIP" as const,
    location: "Salas de Mentoría",
    isLive: true,
  },
  {
    id: "sch-5",
    programId: "prog-ai-northstar",
    day: 5,
    date: "16 Octubre",
    time: "11:59 PM",
    title: "Cierre Estricto de Entregas (Submissions Deadline)",
    type: "DEADLINE" as const,
    location: "Plataforma Kamino",
    isLive: false,
  },
  {
    id: "sch-6",
    programId: "prog-ai-northstar",
    day: 6,
    date: "17 Octubre",
    time: "02:00 PM",
    title: "Pitch Sessions de Finalistas ante el Jurado",
    type: "PITCH" as const,
    location: "Escenario Demo & Transmisión Global",
    isLive: false,
  },
  {
    id: "sch-7",
    programId: "prog-ai-northstar",
    day: 6,
    date: "17 Octubre",
    time: "06:00 PM",
    title: "Anuncio de Ganadores y Celebración de Cierre",
    type: "JUDGING" as const,
    location: "Terraza de Innovación",
    isLive: false,
  },
];

export const DEMO_MENTORS: Mentor[] = [
  {
    id: "m-01",
    name: "Carlos Peña",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80",
    company: "Northstar Labs",
    role: "VP of Engineering",
    skills: ["Arquitectura Cloud", "Seguridad", "Escalamiento", "FastAPI"],
    status: "IN_SESSION",
    assignedTeamIds: ["team-docuflow"],
    totalSessions: 14,
  },
  {
    id: "m-02",
    name: "Elena Sandoval",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80",
    company: "Andes Ventures",
    role: "Partner & Head of Product",
    skills: ["Modelos de Negocio", "Pitching", "B2B SaaS", "Unit Economics"],
    status: "AVAILABLE",
    assignedTeamIds: ["team-neural-andes"],
    totalSessions: 19,
  },
  {
    id: "m-03",
    name: "Julián Cárdenas",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80",
    company: "VectorAI Research",
    role: "Lead Research Scientist",
    skills: ["RAG Avanzado", "Embeddings", "Evaluación de LLMs", "PyTorch"],
    status: "CONFIRMED",
    assignedTeamIds: ["team-logix-ai"],
    totalSessions: 8,
  },
];

export const DEMO_MENTOR_SESSIONS: MentorSession[] = [
  {
    id: "ms-1",
    mentorId: "m-01",
    teamId: "team-docuflow",
    teamName: "DocuFlow AI",
    programId: "prog-ai-northstar",
    time: "Hoy, 15:30 (30 min)",
    topic: "Optimización de latencia en pipeline de inferencia y salvaguardas de datos sensibles.",
    notes: "Equipo muy enfocado. Les recomendé separar el pre-procesamiento OCR en worker background con Redis.",
    status: "ACTIVE",
  },
  {
    id: "ms-2",
    mentorId: "m-02",
    teamId: "team-neural-andes",
    teamName: "Neural Andes",
    programId: "prog-ai-northstar",
    time: "Hoy, 16:30 (30 min)",
    topic: "Definición del modelo de tarificación para clientes B2B.",
    notes: "Revisar si su pricing por token o por documento procesado es más comprensible para CFOs.",
    status: "SCHEDULED",
  },
  {
    id: "ms-3",
    mentorId: "m-03",
    teamId: "team-logix-ai",
    teamName: "Logix Dynamic Dispatch",
    programId: "prog-ai-northstar",
    time: "Hoy, 17:30 (30 min)",
    topic: "Selección del algoritmo de ruteo dinámico con restricciones temporales.",
    status: "SCHEDULED",
  },
];

export const DEMO_APPLICATIONS: DemoApplication[] = [
  {
    id: "app-101",
    name: "Mateo Valencia",
    email: "mateo@valencia.tech",
    city: "Bogotá",
    role: "Fullstack",
    skills: ["TypeScript", "Next.js", "Python"],
    status: "ACCEPTED" as const,
    teamName: "DocuFlow AI",
    appliedAt: "2026-10-02",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
    experience: "5 años construyendo SaaS B2B",
  },
  {
    id: "app-102",
    name: "Camila Restrepo",
    email: "camila@restrepo.design",
    city: "Medellín",
    role: "UX/Design",
    skills: ["Figma", "Design Systems", "Tailwind"],
    status: "ACCEPTED" as const,
    teamName: "Neural Andes",
    appliedAt: "2026-10-03",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80",
    experience: "Lead Designer en Fintech",
  },
  {
    id: "app-103",
    name: "Andrés Echeverry",
    email: "andres@echeverry.ai",
    city: "Cali",
    role: "AI/ML",
    skills: ["Python", "PyTorch", "LangChain"],
    status: "ACCEPTED" as const,
    teamName: "DocuFlow AI",
    appliedAt: "2026-10-01",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    experience: "Investigador en NLP y modelos generativos",
  },
  {
    id: "app-104",
    name: "Daniela Morales",
    email: "daniela.pm@outlook.com",
    city: "Bogotá",
    role: "Product",
    skills: ["Discovery", "Pitching", "Growth"],
    status: "UNDER_REVIEW" as const,
    teamName: "Sin equipo (buscando)",
    appliedAt: "2026-10-04",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80",
    experience: "PM en e-commerce regional",
  },
  {
    id: "app-105",
    name: "Santiago Orozco",
    email: "santiago@orozco.io",
    city: "Bucaramanga",
    role: "Backend",
    skills: ["Go", "Kafka", "AWS"],
    status: "ACCEPTED" as const,
    teamName: "Logix Dynamic Dispatch",
    appliedAt: "2026-10-03",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
    experience: "Ingeniero backend de alto rendimiento",
  },
  {
    id: "app-106",
    name: "Valentina Pardo",
    email: "vpardo@uniandes.edu.co",
    city: "Bogotá",
    role: "Data Science",
    skills: ["R", "Python", "Tableau"],
    status: "UNDER_REVIEW" as const,
    teamName: "Sin equipo (buscando)",
    appliedAt: "2026-10-04",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
    experience: "Candidata a Maestría en Analítica",
  },
  {
    id: "app-107",
    name: "Nicolás Bernal",
    email: "nicolas@bernal.co",
    city: "Manizales",
    role: "Frontend",
    skills: ["React", "Vue", "TypeScript"],
    status: "WAITLISTED" as const,
    teamName: "Sin equipo",
    appliedAt: "2026-10-05",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80",
    experience: "Desarrollador web junior con portafolio",
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    title: "¡Postulación Aprobada!",
    message: "Tu aplicación a Bogotá AI Operations Challenge ha sido aceptada. Completa la conformación de tu equipo.",
    timestamp: "Hace 2 horas",
    read: false,
    link: "/app/hackathons/bogota-ai-operations",
    type: "STATUS",
  },
  {
    id: "notif-2",
    title: "Invitación de Equipo",
    message: "Mateo Valencia te ha invitado a unirte a 'DocuFlow AI' como Product Designer.",
    timestamp: "Hace 4 horas",
    read: false,
    link: "/app/hackathons/bogota-ai-operations/team",
    type: "INVITE",
  },
  {
    id: "notif-3",
    title: "Sesión de Mentoría Agendada",
    message: "Tu sesión con Carlos Peña (VP Engineering) inicia hoy a las 15:30.",
    timestamp: "Hace 5 horas",
    read: true,
    link: "/app/hackathons/bogota-ai-operations",
    type: "ANNOUNCEMENT",
  },
  {
    id: "notif-4",
    title: "Recordatorio de Entrega",
    message: "Quedan 48 horas para el cierre definitivo de proyectos.",
    timestamp: "Ayer",
    read: true,
    link: "/app/hackathons/bogota-ai-operations/submission",
    type: "DEADLINE",
  },
];
